### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by Webmasterei** [Nosto/nosto-magento#183]
Hi,
using the composer installation I get following error:
[ErrorException]                                                                                                 
  Source .../vendor/nosto/nosto-magento-extension/lib/nosto/* does not exist

**Comment by hannunosto** [comment]
Hi @Webmasterei, If you are trying to include this repo with [magento-composer-installer](https://github.com/Cotya/magento-composer-installer) or with normal composer there might be problem with our PHP SDK dependency as the SDK must be included inside `lib` directory within the extension. This is due to the fact that Magento was not really built to support composer installations. Anyways, you can use our "no dependecies" repo with composer. This repo has PHP SDK already included and it can be found from [here](https://github.com/Nosto/nosto-magento-nodeps)

If you just want to checkout this repo into your Magento installation, please use [these instructions from our wiki](https://github.com/Nosto/nosto-magento/wiki/Installing#modman)
