### ISSUE TITLE
Only one category reported in product.phtml

### ISSUE THREAD

**Issue by lahdekorpi** [Nosto/nosto-magento#401]
https://github.com/Nosto/nosto-magento/blob/678a499e19b568538cf5f3464b55ec90ef4560d0/app/design/frontend/base/default/template/nostotagging/product.phtml#L149

If a product exists in multiple categories, `getCurrentCategory()` only reports the current category based on the path.  
If the user opens the page from, for example, a campaign page, search or front page, the only reported category to Nosto would be said page.

The expected functionality would be to send all the categories that the product belongs to.

**Comment by hannunosto** [comment]
Hey @lahdekorpi, the div having class `nosto_category` is more of a current active category rather than a product category list. This category will be based on visitor's navigation history. The actual product categories will be outputted here: https://github.com/Nosto/nosto-magento/blob/678a499e19b568538cf5f3464b55ec90ef4560d0/app/design/frontend/base/default/template/nostotagging/product.phtml#L61

**Comment by lahdekorpi** [comment]
Thanks for the clarification!
